[package]
name = "Amano"
version = "0.1.0"
authors = ["Andrew Polican <adpolican@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2.0"
itertools = "0.10.0"
args = "2.0"
getopts = "0.2"
